# Configuraciones varias
spring.application.name=workout-tracker

# Configuraciones de BD
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/workout_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Config de JWT
security.jwt.private.key=mi_clave_secreta_super_segura_para_el_token_jwt_12345
security.jwt.user.generator=workout_tracker_app

# Puerto del servidor
server.port=9090
